### PR TITLE
Attempted to fix a problem with not finding cfitsio.

### PR DESCRIPTION
**Pull request by rbmetcalf**
@gdespali @michalbilek @ntessore 
I think I made a mistake when updating the CMakeList.txt file.

If you would pull this new branch, ie. from your top Glamer directory
```
git pull
git checkout fix_cfitsio -t
```

And then try to run cmake again.  Let me know what happens here.

### CODE REVIEW

**Comment by michalbilek** [comment]
The second command gives:
fatal: Missing branch name; try -b

**Comment by rbmetcalf** [comment]
Strange.  What do you get when you do `git branch -a`?

**Comment by michalbilek** [comment]
git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/fix_cfitsio
  remotes/origin/gh-pages
  remotes/origin/master
  remotes/origin/noCCFITS

**Comment by rbmetcalf** [comment]
ok it should be
`git checkout origin/fix_cfitsio -t`

**Comment by michalbilek** [comment]
It seems that Glamer has been installed now, thanks a lot!

**Comment by rbmetcalf** [comment]
So `make` ran okay?

**Comment by rbmetcalf** [comment]
@gdespali let me know if this works for you.

**Comment by michalbilek** [comment]
There were just a few warnings during the building. There was nothing suspicious written at the end of the output.

**Comment by rbmetcalf** [comment]
Great!

**Comment by gdespali** [comment]
Thanks!
almost solved, the error is not there anymore and cmake works. Now I get an error on the location of fitsio.h when doing make, but could be due to the library on the cluster. I'll update you later!

**Comment by rbmetcalf** [comment]
Yes, but there should be a way of setting the paths by hand. I'll work on it...

**Pull request merged**
